import { 
  ChevronDown, 
  ChevronRight,
  X,
  Home,
  Users,
  BookOpen,
  Calendar,
  ClipboardCheck,
  Settings,
  GraduationCap,
  FileText,
  Award,
  Book,
  Briefcase,
  DollarSign,
  CreditCard,
  Clock,
  FileSpreadsheet,
  UserCheck,
  ClipboardList,
  Receipt,
  PieChart,
  ListChecks,
  Building,
  Cog,
  LogOut
} from 'lucide-react';

export const icons = {
  home: Home,
  users: Users,
  bookOpen: BookOpen,
  calendar: Calendar,
  clipboardCheck: ClipboardCheck,
  settings: Settings,
  graduationCap: GraduationCap,
  fileText: FileText,
  award: Award,
  book: Book,
  briefcase: Briefcase,
  dollarSign: DollarSign,
  creditCard: CreditCard,
  clock: Clock,
  fileSpreadsheet: FileSpreadsheet,
  userCheck: UserCheck,
  clipboardList: ClipboardList,
  receipt: Receipt,
  pieChart: PieChart,
  listChecks: ListChecks,
  building: Building,
  cog: Cog,
  logOut: LogOut,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  x: X
};
